
package com.finalproject.maindashboard;

import com.finalproject.aboutproject.About;
import com.finalproject.help.Help;
import com.finalproject.Stegnography.DembedForm;
import com.finalproject.Stegnography.EmbedForm;
import com.finalproject.compression.CompressForm;
import com.finalproject.compression.DecompressForm;
import com.finalproject.compression.ZipForm;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.finalproject.encryptiondecryptiongui.Main;



/**
 *
 * @author root
 */
public class SteganographyPanel extends javax.swing.JPanel {
     private Help help;
     private About about;
     private DembedForm dembedForm;
     private CompressForm compressForm;
     private DecompressForm decompressForm;
     private EmbedForm embeddForm;
    

    /**
     * Creates new form SteganographyPanel
     */
    public SteganographyPanel() {
        initComponents();
        encryptionBtn.setToolTipText("proceed to encrypt or de-encrypt file(s)");
        embedBtn.setToolTipText("embed message into a video file");
        dembedBtn.setToolTipText("extract hidden file from the video");
        compressBtn.setToolTipText("reduce the size of a file");
        decompressBtn.setToolTipText("decompress file to get it's original size");
        zipBtn.setToolTipText("make a zip file");
    }

  @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/bg2.jpg"));
        g.drawImage(icon.getImage(), 0, 0, getWidth(), getHeight(), this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file_chooser = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        compressBtn = new javax.swing.JButton();
        decompressBtn = new javax.swing.JButton();
        embedBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        dembedBtn = new javax.swing.JButton();
        zipBtn = new javax.swing.JButton();
        encryptionBtn = new javax.swing.JButton();

        file_chooser.setCurrentDirectory(new java.io.File("C:\\Users\\root\\Documents\\NetBeansProjects\\RahamaProject"));

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(800, 450));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(750, 550));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Video Steganography");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("About ");
        jButton1.setToolTipText("About The Software");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setText("Help");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        compressBtn.setBackground(new java.awt.Color(255, 255, 255));
        compressBtn.setForeground(new java.awt.Color(0, 102, 204));
        compressBtn.setText("COMPRESS");
        compressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compressBtnActionPerformed(evt);
            }
        });

        decompressBtn.setBackground(new java.awt.Color(255, 255, 255));
        decompressBtn.setForeground(new java.awt.Color(0, 102, 204));
        decompressBtn.setText("DECOMPRESS");
        decompressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decompressBtnActionPerformed(evt);
            }
        });

        embedBtn.setBackground(new java.awt.Color(255, 255, 255));
        embedBtn.setForeground(new java.awt.Color(0, 102, 204));
        embedBtn.setText("EMBED");
        embedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                embedBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Security");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Compression");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Steganography");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Zip");

        jButton9.setBackground(new java.awt.Color(66, 121, 151));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/off.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        dembedBtn.setBackground(new java.awt.Color(255, 255, 255));
        dembedBtn.setForeground(new java.awt.Color(0, 102, 204));
        dembedBtn.setText("DE-EMBED");
        dembedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dembedBtnActionPerformed(evt);
            }
        });

        zipBtn.setBackground(new java.awt.Color(255, 255, 255));
        zipBtn.setForeground(new java.awt.Color(0, 102, 204));
        zipBtn.setText("ZIP");
        zipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipBtnActionPerformed(evt);
            }
        });

        encryptionBtn.setBackground(new java.awt.Color(255, 255, 255));
        encryptionBtn.setForeground(new java.awt.Color(0, 51, 255));
        encryptionBtn.setText("ENCRYPT OR DECRYPT FILE(S)");
        encryptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(embedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(compressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decompressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(dembedBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(zipBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(encryptionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compressBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decompressBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(embedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dembedBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zipBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        help = new Help();
        help.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void compressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compressBtnActionPerformed
        // TODO add your handling code here:
        compressForm = new CompressForm();
        compressForm.setVisible(true);
         
    }//GEN-LAST:event_compressBtnActionPerformed

    private void decompressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decompressBtnActionPerformed
        // TODO add your handling code here:
         decompressForm = new DecompressForm();
        decompressForm.setVisible(true);
         
    }//GEN-LAST:event_decompressBtnActionPerformed

    private void embedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_embedBtnActionPerformed
        // TODO add your handling code here:
         embeddForm = new EmbedForm();
        embeddForm.setVisible(true);
    }//GEN-LAST:event_embedBtnActionPerformed

    private void dembedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dembedBtnActionPerformed
        // TODO add your handling code here:
        dembedForm = new DembedForm();
        dembedForm.setVisible(true);
    }//GEN-LAST:event_dembedBtnActionPerformed

    private void zipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipBtnActionPerformed
      ZipForm zipform = new ZipForm();
      zipform.setVisible(true);
      
    }//GEN-LAST:event_zipBtnActionPerformed

    private void encryptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptionBtnActionPerformed
    final boolean user = false;
        Main main = new Main(user);
        main.setVisible(true);
    }//GEN-LAST:event_encryptionBtnActionPerformed

    
    
    
    
    
    
    void openFile(){
        String name = "";
        int openfiledailog = file_chooser.showOpenDialog(this);

        //check if the user closes the dailog without chooosing any file
        if (openfiledailog == JFileChooser.CANCEL_OPTION) {
            displayInfo("No File Selected!!!");
        } else {
            

            name = file_chooser.getSelectedFile().getName();

            if (!(name.endsWith(".flv"))) {
                displayInfo("Please only flv videos!!!");
            } else {
//                txt_ouput_f_name.setText(name);

            }

        }
    }
    private void displayInfo(String messageToDisplay) {
        JOptionPane.showMessageDialog(this, messageToDisplay, "WARNING!!!", JOptionPane.ERROR_MESSAGE);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton compressBtn;
    private javax.swing.JButton decompressBtn;
    private javax.swing.JButton dembedBtn;
    private javax.swing.JButton embedBtn;
    private javax.swing.JButton encryptionBtn;
    private javax.swing.JFileChooser file_chooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton zipBtn;
    // End of variables declaration//GEN-END:variables
}
