package com.finalproject.help;
import java.awt.FileDialog;
import java.awt.Toolkit;

/*
 * CRCForm.java
 *
 * Created on November 3, 2007, 12:12 PM
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author  Administrator
 */
public class Help extends javax.swing.JFrame {
     
    /** Creates new form CRCForm */
    public Help() {
        initComponents();
        int lebar = this.getWidth()/2;
    int tinggi = this.getHeight()/2;
    int x = (Toolkit.getDefaultToolkit().getScreenSize().width/2)-lebar;
    int y = (Toolkit.getDefaultToolkit().getScreenSize().height/2)-tinggi;
    this.setLocation(x, y);
          getContentPane().setBackground(new java.awt.Color(66, 121, 151));
 }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VideoSteganoGraphy---DeEmbeding Video File");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel5.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Help");

        jLabel9.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N

        jTextArea2.setBackground(new java.awt.Color(0, 102, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("STEPS TO EMBEDD A SECURED MESSAGE INTO A VIDEO FILE.\n\n1.Click on the 'Security' menu and choose the \nencryption submenu. Browse to select your message and\nenter your public key 'n' and 'e'. Click on encrypt\nbutton afterwards to encrypt. \n\n2. Click on the 'HuffmanCompression' menu and choose \nthe compression sub-menu. Browse to select your encrypted\nmessage and click on compress button afterwards to \ncompress. \n\n3. Click on the 'Ste Utility' menu and choose \nthe 'Embedd' sub-menu. Browse to select your compressed\nand encrypted message. Click on embedd button \nafterwards to embedd.\n \n\nSTEPS TO DE-EMBEDD A SECURED MESSAGE EMBEDDED\nINTO A VIDEO FILE.\n\n1. Click on the 'Ste Utility' menu and choose \nthe 'De-Embedd' sub-menu. Browse to select your \nembedded video file. Enter the private key 'n' and 'd'\nClick on de-embedd button to de-embedd.\n\n2. Click on the 'Ste Utility' menu and choose \nthe 'Embedd' sub-menu. Browse to select your compressed\nand encrypted message. Click on embedd button \nafterwards to embedd.\n\n3. Click on the 'Security' menu and choose the \ndecryption submenu. Browse to select your encrypted\nmessage and enter your private key 'n' and 'd'. \nClick on decrypt button afterwards to decrypt. \n");
        jScrollPane2.setViewportView(jTextArea2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(152, 152, 152)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(147, 147, 147)
                        .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(129, 129, 129))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 256, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    
}
